// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAto5mim6Xch2QxuaYrk1faF3qsA5vG8Fk',
    appId: '1:727924751929:web:125918f43ca0351e0317e8',
    messagingSenderId: '727924751929',
    projectId: 'the-cook-book-cb',
    authDomain: 'the-cook-book-cb.firebaseapp.com',
    storageBucket: 'the-cook-book-cb.appspot.com',
    measurementId: 'G-Q88VNN72E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWHH9jO-irRkW4f_YiQKQG6G7N0uy0aQ',
    appId: '1:727924751929:android:b7279c73f2107de20317e8',
    messagingSenderId: '727924751929',
    projectId: 'the-cook-book-cb',
    storageBucket: 'the-cook-book-cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaMuuC_DtqZ0ki7c33yXKaqtqtru4eRGc',
    appId: '1:727924751929:ios:0259599c6af013760317e8',
    messagingSenderId: '727924751929',
    projectId: 'the-cook-book-cb',
    storageBucket: 'the-cook-book-cb.appspot.com',
    iosClientId: '727924751929-nmuisropl97kl12pmo0911pf4a5cmg18.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaMuuC_DtqZ0ki7c33yXKaqtqtru4eRGc',
    appId: '1:727924751929:ios:0259599c6af013760317e8',
    messagingSenderId: '727924751929',
    projectId: 'the-cook-book-cb',
    storageBucket: 'the-cook-book-cb.appspot.com',
    iosClientId: '727924751929-nmuisropl97kl12pmo0911pf4a5cmg18.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookbook',
  );
}
